image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      export PATH=$HOME/miniconda/bin:$PATH
      conda env create -f environment.yml
  - command: |
      export PATH=$HOME/miniconda/bin:$PATH
      conda activate my-conda-env && python --version

ports:
  - port: 8888
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
