image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      conda env create -f environment.yml
      conda activate my-conda-env
  - command: python --version

ports:
  - port: 8888
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
